In [38]:
using Interpolations

In [39]:
A = zeros(10,10,5,5)
for i in 1:10
    for j in 1:10
        for k in 1:5
            for l in 1:5
                A[i,j,k,l] = sin((0.6^4)*i*j*k*l)
            end
        end
    end
end
itp = interpolate(A, BSpline(Cubic(Line(OnGrid()))))
itp1 = interpolate(A, BSpline(Linear()))
print(" ")

In [ ]:
itp = interpolate(A, BSpline(Cubic(Line(OnGrid()))))
ils = 1:0.1:10
jls = 1:0.1:10
kls = 1:0.1:5
lls = 1:0.1:5
N = length(ils)
N2 = length(lls)
acc = zeros(N,N,N2,N2)
for i in 1:N
    for j in 1:N
        for k in 1:N2
            for l in 1:N2
                acc[i,j,k,l] = itp(ils[i],jls[j],kls[k],lls[l])
            end
        end
    end
end
using Plots
Plots.heatmap(acc[:,:,1,1])

In [128]:
include("MOMDPs.jl")

# define scaling 
m = [5,5,5]
mean_bounds=zeros(2,1);mean_bounds[2,1]=1.0
var_bounds=zeros(2,1);var_bounds[1,1]=0.01;var_bounds[2,1]=1.0
cor_bounds = 0.5
obs_bounds=zeros(2,1);obs_bounds[2,1]=1.0
scale = MOMDPs.init_scaling(m,mean_bounds,var_bounds,cor_bounds,obs_bounds)

# initialize value function 
V = MOMDPs.init_value_function(scale)
print(" ")

In [ ]:
v = zeros(3)
V.values = broadcast(i->sin(prod((0.2^3)*MOMDPs.state_to_node!(v,V.nodes[i],scale))), 1:125)
MOMDPs.update!(V)

In [136]:
B = MOMDPs.beleif_state([0.1],[0.55;;],[0.55;;],[0.75])

Main.MOMDPs.beleif_state([0.1], [0.55;;], [0.55;;], [0.75])

In [35]:
# define beleif state
M= zeros(1,1)
M[1,1] = 1.0
mean = [0.1]
# define scaling
B = beleif_state(mean,M,deepcopy(M),[0.5])
dims = zeros(2,1)
dims[2,1]=0.5

dims_v = zeros(2,1)
dims_v[1,1] = 0.05
dims_v[2,1] = 1.0
scale = MOMDPs.init_scaling(m,mean_bounds,var_bounds,cor_bounds,obs_bounds)
state_to_node!(zeros(3),B,scale)
@time state_to_node!(zeros(3),B,scale)

  0.000170 seconds (84 allocations: 3.234 KiB)


1-element view(::Vector{Float64}, 3:3) with eltype Float64:
 3.0

In [36]:
V = init_value_function(scale;n_nodes_max = 10^5)

value_function(scaling([3, 3, 3], [0.0; 0.5;;], [0.05; 1.0;;], 0.5, [0.0; 0.5;;]), beleif_state[beleif_state([0.0], [0.05;;], [0.0;;], [0.0]), beleif_state([0.0], [0.05;;], [0.0;;], [0.25]), beleif_state([0.0], [0.05;;], [0.0;;], [0.5]), beleif_state([0.0], [0.525;;], [0.0;;], [0.0]), beleif_state([0.0], [0.525;;], [0.0;;], [0.25]), beleif_state([0.0], [0.525;;], [0.0;;], [0.5]), beleif_state([0.0], [1.0;;], [0.0;;], [0.0]), beleif_state([0.0], [1.0;;], [0.0;;], [0.25]), beleif_state([0.0], [1.0;;], [0.0;;], [0.5]), beleif_state([0.25], [0.05;;], [0.0;;], [0.0])  …  beleif_state([0.25], [1.0;;], [0.0;;], [0.5]), beleif_state([0.5], [0.05;;], [0.0;;], [0.0]), beleif_state([0.5], [0.05;;], [0.0;;], [0.25]), beleif_state([0.5], [0.05;;], [0.0;;], [0.5]), beleif_state([0.5], [0.525;;], [0.0;;], [0.0]), beleif_state([0.5], [0.525;;], [0.0;;], [0.25]), beleif_state([0.5], [0.525;;], [0.0;;], [0.5]), beleif_state([0.5], [1.0;;], [0.0;;], [0.0]), beleif_state([0.5], [1.0;;], [0.0;;], [0.25]), 

In [37]:
V.nodes

27-element Vector{beleif_state}:
 beleif_state([0.0], [0.05;;], [0.0;;], [0.0])
 beleif_state([0.0], [0.05;;], [0.0;;], [0.25])
 beleif_state([0.0], [0.05;;], [0.0;;], [0.5])
 beleif_state([0.0], [0.525;;], [0.0;;], [0.0])
 beleif_state([0.0], [0.525;;], [0.0;;], [0.25])
 beleif_state([0.0], [0.525;;], [0.0;;], [0.5])
 beleif_state([0.0], [1.0;;], [0.0;;], [0.0])
 beleif_state([0.0], [1.0;;], [0.0;;], [0.25])
 beleif_state([0.0], [1.0;;], [0.0;;], [0.5])
 beleif_state([0.25], [0.05;;], [0.0;;], [0.0])
 beleif_state([0.25], [0.05;;], [0.0;;], [0.25])
 beleif_state([0.25], [0.05;;], [0.0;;], [0.5])
 beleif_state([0.25], [0.525;;], [0.0;;], [0.0])
 ⋮
 beleif_state([0.25], [1.0;;], [0.0;;], [0.0])
 beleif_state([0.25], [1.0;;], [0.0;;], [0.25])
 beleif_state([0.25], [1.0;;], [0.0;;], [0.5])
 beleif_state([0.5], [0.05;;], [0.0;;], [0.0])
 beleif_state([0.5], [0.05;;], [0.0;;], [0.25])
 beleif_state([0.5], [0.05;;], [0.0;;], [0.5])
 beleif_state([0.5], [0.525;;], [0.0;;], [0.0])
 beleif_stat

In [12]:
using FastGaussQuadrature 
nodes, weights = FastGaussQuadrature.gausshermite(20)
weights_unscaled = weights
weights = weights .* (2*pi)^(-1/2).*exp.((nodes.^2)./2)

20-element Vector{Float64}:
 1.7856021898799043e-7
 7.022518386313846e-6
 0.0001037125506840011
 0.0008452039867178815
 0.004449784091912226
 0.01644880130922808
 0.04486176834756882
 0.09313399313962073
 0.15010666624939442
 0.19004286914528676
 0.19004286914528676
 0.15010666624939442
 0.09313399313962073
 0.04486176834756882
 0.01644880130922808
 0.004449784091912226
 0.0008452039867178815
 0.0001037125506840011
 7.022518386313846e-6
 1.7856021898799043e-7

In [10]:
mu = 100
sigma2 = 10
x = sqrt(sigma2)*(nodes).+mu
println(sum(x.*weights))
println(sum((x .-mu ).^ 2 .* weights))

99.99999997980363
9.999999892297218


In [19]:
x = sqrt(2)*sqrt(sigma2)*(nodes).+mu 
println(sum(x.*weights_unscaled)/sqrt(pi))
println(sum((x .- mu ) .^2 .*weights_unscaled)/sqrt(pi))

100.00000000000001
10.000000000000126


In [27]:
nodes, weights = FastGaussQuadrature.gausshermite(10)

([-3.4361591188377374, -2.5327316742327897, -1.7566836492998803, -1.0366108297895167, -0.34290132722370714, 0.34290132722370714, 1.0366108297895167, 1.7566836492998803, 2.5327316742327897, 3.4361591188377374], [7.640432855232609e-6, 0.0013436457467812285, 0.03387439445548132, 0.24013861108231485, 0.610862633735325, 0.610862633735325, 0.24013861108231485, 0.03387439445548132, 0.0013436457467812285, 7.640432855232609e-6])

In [17]:
weights = weights .* (2*pi)^(-1/2).*exp.((nodes.^2)./2)
println(weights)

[0.16320570558280115, 0.13061307064540434, 0.11800414848442334, 0.11193308628050136, 0.10935247336508891, 0.10935247336508891, 0.11193308628050136, 0.11800414848442334, 0.13061307064540434, 0.16320570558280115]


In [4]:
function add(x; y = length(x))
    y * x
end

add (generic function with 1 method)

In [5]:
add([2.0,3.0])

2-element Vector{Float64}:
 4.0
 6.0